-- MySQL Script generated by MySQL Workbench
-- Tue Jun 16 16:39:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8 ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `streetAddress` VARCHAR(60) NOT NULL,
  `numberAddress` INT NOT NULL,
  `floorAddress` VARCHAR(10) NULL,
  `doorAddress` INT NULL,
  `cityAddress` VARCHAR(45) NOT NULL,
  `zipCodeAddress` INT(10) NOT NULL,
  `contryAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `nameSupplier` VARCHAR(45) NOT NULL,
  `phoneSupplier` VARCHAR(11) NOT NULL,
  `faxSupplier` VARCHAR(11) NOT NULL,
  `nifSupplier` VARCHAR(9) NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  INDEX `fk_Supplier_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `Optica`.`Address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `nameBrand` VARCHAR(45) NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idBrand`, `Supplier_idSupplier`),
  INDEX `fk_Brand_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `Optica`.`Supplier` (`idSupplier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Glasses` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `graduationGlasses` FLOAT NOT NULL,
  `frameGlasses` VARCHAR(8) NOT NULL,
  `colorFrameGlasses` VARCHAR(20) NOT NULL,
  `colorGlassGlasses` VARCHAR(20) NOT NULL,
  `priceGlasses` FLOAT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_Glasses_Brand_idx` (`Brand_idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Brand`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `Optica`.`Brand` (`idBrand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Costumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Costumer` (
  `idCostumer` INT NOT NULL AUTO_INCREMENT,
  `nameCostumer` VARCHAR(45) NOT NULL,
  `zipCodeCostumer` VARCHAR(10) NOT NULL,
  `phoneCostumer` VARCHAR(11) NOT NULL,
  `emailCostumer` VARCHAR(100) NULL,
  `registrationDateCostumer` DATETIME NOT NULL,
  `recommendationCostumer` VARCHAR(45) NULL,
  PRIMARY KEY (`idCostumer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `nameEmployee` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Sale` (
  `idSale` INT NOT NULL AUTO_INCREMENT,
  `Costumer_idCostumer` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idSale`),
  INDEX `fk_Sale_Costumer1_idx` (`Costumer_idCostumer` ASC) VISIBLE,
  INDEX `fk_Sale_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Costumer1`
    FOREIGN KEY (`Costumer_idCostumer`)
    REFERENCES `Optica`.`Costumer` (`idCostumer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sale_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Optica`.`Employee` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`ItemSale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`ItemSale` (
  `Sale_idSale` INT NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  INDEX `fk_ItemSale_Sale1_idx` (`Sale_idSale` ASC) VISIBLE,
  INDEX `fk_ItemSale_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  PRIMARY KEY (`Sale_idSale`, `Glasses_idGlasses`),
  CONSTRAINT `fk_ItemSale_Sale1`
    FOREIGN KEY (`Sale_idSale`)
    REFERENCES `Optica`.`Sale` (`idSale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ItemSale_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `Optica`.`Glasses` (`idGlasses`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
